### PR TITLE
Compilable. Functioning.

### PR DESCRIPTION
**Pull request by CrimsonMaple**
I Made a Compilable functioning release. Your welcome, lol. Learn how ReiNand works and make a compilable release before you go public in the future. Don't make people compile/fix shit for you.

### CODE REVIEW

**Comment by CrimsonMaple** [comment]
By release I mean go public with a project lol. Ive had RenNand in secret for months.

**Comment by Pixilate** [comment]
I'm moving things to a new repo. And yeah I've worked privately in so long I forget about making it public. New repo at https://github.com/Pixilate/Reinand-Plus-RE

**Comment by CrimsonMaple** [comment]
cool sounds good. oh you can steal the compiled binaries for a release if you need. im off to work on ReiNand now, lol. Spent too long trying to compile this because i was testing 11.2 nfirm stuff.

**Comment by Pixilate** [comment]
haha thanks :p

**Pull request closed without merging**
